const fs = require('fs');
const path = require('path');
const ExcelJS = require('exceljs');
const PDFDocument = require('pdfkit');
const { REPORT_TITLES, TIME_ZONE } = require('./reportService');

const SENSITIVE_FIELDS = /password|secret|token|recovery|descriptor|otp|hash/i;
const MAX_EXPORT_ROWS = 5_000;

function humanize(value) {
  return String(value)
    .replace(/([a-z])([A-Z])/g, '$1 $2')
    .replace(/[_-]+/g, ' ')
    .replace(/^\w|\s\w/g, (character) => character.toUpperCase());
}

function displayValue(value) {
  if (value === null || value === undefined || value === '') return '—';
  if (value instanceof Date) return value.toISOString();
  if (Array.isArray(value)) return value.map(displayValue).join(', ');
  if (typeof value === 'object') return JSON.stringify(value);
  return String(value);
}

function excelSafe(value) {
  const text = displayValue(value);
  return /^[=+\-@\t\r]/.test(text) ? `'${text}` : text;
}

function columnsFor(records) {
  const keys = records.length ? Object.keys(records[0]) : [];
  return keys.filter((key) => !SENSITIVE_FIELDS.test(key) && key !== 'coverUrl');
}

function generatedDate() {
  return new Intl.DateTimeFormat('en-GB', {
    timeZone: TIME_ZONE,
    dateStyle: 'medium',
    timeStyle: 'medium',
  }).format(new Date());
}

async function createExcel({ type, data, generatedBy }) {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = 'Norton E-Library';
  workbook.created = new Date();
  const title = REPORT_TITLES[type] || humanize(type);
  const records = data.records.slice(0, MAX_EXPORT_ROWS);
  const columns = columnsFor(records);

  const summarySheet = workbook.addWorksheet('Report Summary');
  summarySheet.addRow([title]);
  summarySheet.addRow(['Generated at', generatedDate()]);
  summarySheet.addRow(['Generated by', generatedBy]);
  summarySheet.addRow(['Date range', `${data.filters.startDate} to ${data.filters.endDate}`]);
  summarySheet.addRow(['Total records', data.pagination.totalItems]);
  summarySheet.addRow([]);
  summarySheet.addRow(['Metric', 'Value']);
  for (const [key, value] of Object.entries(data.summary || {})) {
    summarySheet.addRow([humanize(key), excelSafe(value)]);
  }
  summarySheet.getRow(1).font = { bold: true, size: 16 };
  summarySheet.getRow(7).font = { bold: true };
  summarySheet.columns = [{ width: 34 }, { width: 28 }];

  const detailSheet = workbook.addWorksheet('Detailed Records', { views: [{ state: 'frozen', ySplit: 1 }] });
  detailSheet.columns = columns.map((key) => ({ header: humanize(key), key, width: 18 }));
  for (const record of records) {
    detailSheet.addRow(Object.fromEntries(columns.map((key) => [key, excelSafe(record[key])])));
  }
  detailSheet.getRow(1).font = { bold: true, color: { argb: 'FFFFFFFF' } };
  detailSheet.getRow(1).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF2563A6' } };
  if (columns.length) detailSheet.autoFilter = { from: { row: 1, column: 1 }, to: { row: Math.max(1, records.length + 1), column: columns.length } };
  detailSheet.columns.forEach((column) => {
    let width = String(column.header || '').length + 2;
    column.eachCell?.({ includeEmpty: false }, (cell) => { width = Math.max(width, String(cell.value ?? '').length + 2); });
    column.width = Math.min(Math.max(width, 12), 45);
  });

  const filtersSheet = workbook.addWorksheet('Applied Filters');
  filtersSheet.addRow(['Filter', 'Value']);
  for (const [key, value] of Object.entries(data.filters || {})) {
    if (value !== undefined && value !== null && value !== '') filtersSheet.addRow([humanize(key), excelSafe(value)]);
  }
  filtersSheet.getRow(1).font = { bold: true };
  filtersSheet.columns = [{ width: 28 }, { width: 44 }];

  return workbook.xlsx.writeBuffer();
}

function createPdf({ type, data, generatedBy }) {
  const title = REPORT_TITLES[type] || humanize(type);
  const records = data.records.slice(0, MAX_EXPORT_ROWS);
  const allColumns = columnsFor(records);
  const columns = allColumns.slice(0, 8);

  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', layout: 'landscape', margin: 32, bufferPages: true });
    const chunks = [];
    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('error', reject);
    doc.on('end', () => resolve(Buffer.concat(chunks)));

    const configuredFont = process.env.REPORT_FONT_PATH;
    let latinFont = 'Helvetica';
    let khmerFont = 'Helvetica';
    if (configuredFont && fs.existsSync(configuredFont)) {
      doc.registerFont('ReportFont', configuredFont);
      latinFont = khmerFont = 'ReportFont';
    } else {
      const fontRoot = path.dirname(require.resolve('@fontsource/kantumruy-pro/package.json'));
      doc.registerFont('ReportLatin', path.join(fontRoot, 'files/kantumruy-pro-latin-400-normal.woff'));
      doc.registerFont('ReportKhmer', path.join(fontRoot, 'files/kantumruy-pro-khmer-400-normal.woff'));
      latinFont = 'ReportLatin';
      khmerFont = 'ReportKhmer';
    }
    const selectFont = (value) => doc.font(/[\u1780-\u17ff]/u.test(String(value)) ? khmerFont : latinFont);
    doc.font(latinFont);

    const pageWidth = doc.page.width - doc.page.margins.left - doc.page.margins.right;
    const columnWidth = columns.length ? pageWidth / columns.length : pageWidth;

    const drawBrand = () => {
      doc.font(latinFont);
      doc.fillColor('#2563A6').fontSize(11).text('NORTON UNIVERSITY E-LIBRARY', {
        align: 'center',
        width: pageWidth,
      });
      doc.moveDown(0.4).fillColor('#111827').fontSize(18).text(title, {
        align: 'center',
        width: pageWidth,
      });
      doc.moveDown(0.2).fontSize(8).fillColor('#4B5563')
        .text(`Generated: ${generatedDate()}  |  By: ${generatedBy}  |  ${data.filters.startDate} to ${data.filters.endDate}`, {
          align: 'center',
          width: pageWidth,
        });
      doc.moveDown(0.5);
      const summaryText = Object.entries(data.summary || {}).slice(0, 8)
        .map(([key, value]) => `${humanize(key)}: ${displayValue(value)}`).join('   •   ');
      doc.fontSize(8).text(summaryText, { align: 'center', width: pageWidth });
      doc.moveDown(0.8);
    };

    const drawTableHeader = () => {
      const y = doc.y;
      doc.rect(doc.page.margins.left, y, pageWidth, 22).fill('#2563A6');
      doc.font(latinFont).fillColor('#FFFFFF').fontSize(7);
      columns.forEach((key, index) => doc.text(humanize(key), doc.page.margins.left + index * columnWidth + 3, y + 7, {
        align: 'center',
        width: columnWidth - 6,
        ellipsis: true,
      }));
      doc.y = y + 24;
    };

    drawBrand();
    if (columns.length) drawTableHeader();
    for (const [rowIndex, record] of records.entries()) {
      if (doc.y + 28 > doc.page.height - doc.page.margins.bottom - 16) {
        doc.addPage();
        drawTableHeader();
      }
      const y = doc.y;
      if (rowIndex % 2 === 0) doc.rect(doc.page.margins.left, y, pageWidth, 24).fill('#F3F4F6');
      doc.fillColor('#111827').fontSize(6.5);
      columns.forEach((key, index) => {
        const value = displayValue(record[key]);
        selectFont(value).text(value, doc.page.margins.left + index * columnWidth + 3, y + 5, {
          align: 'center',
          width: columnWidth - 6,
          height: 15,
          ellipsis: true,
        });
      });
      doc.y = y + 24;
    }
    if (!records.length) doc.fillColor('#6B7280').fontSize(11).text('No records match the selected filters.', { align: 'center' });

    const range = doc.bufferedPageRange();
    for (let pageIndex = range.start; pageIndex < range.start + range.count; pageIndex += 1) {
      doc.switchToPage(pageIndex);
      const footerY = doc.page.height - doc.page.margins.bottom - 10;
      doc.font(latinFont).fontSize(7).fillColor('#6B7280')
        .text(
          `Norton E-Library Admin Report  |  Page ${pageIndex + 1} of ${range.count}`,
          doc.page.margins.left,
          footerY,
          { align: 'center', lineBreak: false, width: pageWidth },
        );
    }
    doc.end();
  });
}

async function exportReport({ type, format, data, generatedBy }) {
  const date = new Intl.DateTimeFormat('en-CA', { timeZone: TIME_ZONE }).format(new Date());
  const filename = `norton-elibrary-${type}-report-${date}.${format === 'excel' ? 'xlsx' : 'pdf'}`;
  if (format === 'excel') {
    return {
      filename,
      contentType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
      buffer: Buffer.from(await createExcel({ type, data, generatedBy })),
    };
  }
  return { filename, contentType: 'application/pdf', buffer: await createPdf({ type, data, generatedBy }) };
}

module.exports = { MAX_EXPORT_ROWS, exportReport };
